package net.ucanaccess.jdbc;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class ExecuteUpdate extends AbstractExecute {

    public ExecuteUpdate(UcanaccessPreparedStatement statement) {
        super(statement, CommandType.PREPARED_STATEMENT, null, 0, null, null);
    }

    ExecuteUpdate(UcanaccessStatement statement) {
        super(statement);
    }

    public ExecuteUpdate(UcanaccessStatement statement, String sql) {
        super(statement, CommandType.NO_ARGUMENTS, sql, 0, null, null);
    }

    public ExecuteUpdate(UcanaccessStatement statement, String sql, int autoGeneratedKeys) {
        super(statement, CommandType.WITH_AUTO_GENERATED_KEYS, sql, autoGeneratedKeys, null, null);
    }

    public ExecuteUpdate(UcanaccessStatement statement, String sql, int[] indexes) {
        super(statement, CommandType.WITH_INDEXES, sql, 0, null, indexes);
    }

    public ExecuteUpdate(UcanaccessStatement statement, String sql, String[] columnNames) {
        super(statement, CommandType.WITH_COLUMNS_NAME, sql, 0, columnNames, null);
    }

    public int execute() throws SQLException {
        return (Integer) executeBase();
    }

    public int[] executeBatch() throws SQLException {
        setCommandType(CommandType.BATCH);
        return (int[]) executeBase();
    }

    @Override
    public Object executeWrapped() throws SQLException {
        Statement w = getWrappedStatement();
        switch (getCommandType()) {
        case BATCH:
            return w.executeBatch();
        case PREPARED_STATEMENT:
            return ((PreparedStatement) w).executeUpdate();
        case NO_ARGUMENTS:
            return w.executeUpdate(getSql());
        case WITH_COLUMNS_NAME:
            return w.executeUpdate(getSql(), getColumnNames());
        case WITH_AUTO_GENERATED_KEYS:
            return w.executeUpdate(getSql(), getAutoGeneratedKeys());
        case WITH_INDEXES:
            return w.executeUpdate(getSql(), getIndexes());
        default:
            return 0;
        }
    }
}
