package net.ucanaccess.jdbc;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class Execute extends AbstractExecute {

    public Execute(UcanaccessPreparedStatement statement) {
        super(statement, CommandType.PREPARED_STATEMENT, null, 0, null, null);
    }

    public Execute(UcanaccessStatement statement, String sql) {
        super(statement, CommandType.NO_ARGUMENTS, sql, 0, null, null);
    }

    public Execute(UcanaccessStatement statement, String sql, int autoGeneratedKeys) {
        super(statement, CommandType.WITH_AUTO_GENERATED_KEYS, sql, autoGeneratedKeys, null, null);
    }

    public Execute(UcanaccessStatement statement, String sql, int[] indexes) {
        super(statement, CommandType.WITH_INDEXES, sql, 0, null, indexes);
    }

    public Execute(UcanaccessStatement statement, String sql, String[] columnNames) {
        super(statement, CommandType.WITH_COLUMNS_NAME, sql, 0, columnNames, null);
    }

    public boolean execute() throws SQLException {
        return (Boolean) executeBase();
    }

    @Override
    public Object executeWrapped() throws SQLException {
        Statement w = getWrappedStatement();
        switch (getCommandType()) {
        case PREPARED_STATEMENT:
            return ((PreparedStatement) w).execute();
        case NO_ARGUMENTS:
            return w.execute(getSql());
        case WITH_COLUMNS_NAME:
            return w.execute(getSql(), getColumnNames());
        case WITH_AUTO_GENERATED_KEYS:
            return w.execute(getSql(), getAutoGeneratedKeys());
        case WITH_INDEXES:
            return w.execute(getSql(), getIndexes());
        default:
            return false;
        }
    }

}
