package net.ucanaccess.jdbc;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class ExecuteUpdate extends AbstractExecute {

    public ExecuteUpdate(UcanaccessPreparedStatement _statement) {
        super(_statement, CommandType.PREPARED_STATEMENT, null, 0, null, null);
    }

    ExecuteUpdate(UcanaccessStatement _statement) {
        super(_statement);
    }

    public ExecuteUpdate(UcanaccessStatement _statement, String _sql) {
        super(_statement, CommandType.NO_ARGUMENTS, _sql, 0, null, null);
    }

    public ExecuteUpdate(UcanaccessStatement _statement, String _sql, int _autoGeneratedKeys) {
        super(_statement, CommandType.WITH_AUTO_GENERATED_KEYS, _sql, _autoGeneratedKeys, null, null);
    }

    public ExecuteUpdate(UcanaccessStatement _statement, String _sql, int[] _indexes) {
        super(_statement, CommandType.WITH_INDEXES, _sql, 0, null, _indexes);
    }

    public ExecuteUpdate(UcanaccessStatement _statement, String _sql, String[] _columnNames) {
        super(_statement, CommandType.WITH_COLUMNS_NAME, _sql, 0, _columnNames, null);
    }

    public int execute() throws SQLException {
        return (Integer) executeBase();
    }

    public int[] executeBatch() throws SQLException {
        setCommandType(CommandType.BATCH);
        return (int[]) executeBase();
    }

    @Override
    public Object executeWrapped() throws SQLException {
        Statement w = getWrappedStatement();
        switch (getCommandType()) {
        case BATCH:
            return w.executeBatch();
        case PREPARED_STATEMENT:
            return ((PreparedStatement) w).executeUpdate();
        case NO_ARGUMENTS:
            return w.executeUpdate(getSql());
        case WITH_COLUMNS_NAME:
            return w.executeUpdate(getSql(), getColumnNames());
        case WITH_AUTO_GENERATED_KEYS:
            return w.executeUpdate(getSql(), getAutoGeneratedKeys());
        case WITH_INDEXES:
            return w.executeUpdate(getSql(), getIndexes());
        default:
            return 0;
        }
    }
}
