blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/spannm/ucanaccess/discussions
    about: Have a question rather than a bug or feature request? Ask here.
